/* Replace with your SQL commands */
create table
  if not exists professional_skills (
    id serial primary key,
    professional_skills varchar(255) not null,
    entity_meta_table varchar(255) not null,
    constraint fk_entity_meta_table foreign key (entity_meta_table) references entity_meta (table_name) on delete cascade
  );

-- entity_meta
insert into
  entity_meta (
    display_name,
    description,
    table_name,
    standalone,
    custom
  )
values
  ('Professional Skills', '', 'professional_skills', true, false);

-- column_meta
insert into
  column_meta (
    display_name,
    description,
    example,
    column_name,
    data_type,
    gen_opts_name,
    entity_meta_table
  )
values
  (
    'Professional Skills',
    'Professional Skills that are useful for a job or in life',
    'Cooking, Driving, C++ programming',
    'professional_skills',
    'varchar(255)',
    'entityVarchar',
    'professional_skills'
  );

INSERT INTO
  professional_skills (professional_skills, entity_meta_table)
VALUES
  ('Cooking', 'professional_skills'),
  ('Driving', 'professional_skills'),
  ('C++ programming', 'professional_skills'),
('Project Management', 'professional_skills'),
('Data Analysis', 'professional_skills'),
('Graphic Design', 'professional_skills'),
('Financial Analysis', 'professional_skills'),
('Digital Marketing', 'professional_skills'),
('Carpentry', 'professional_skills'),
('Accounting', 'professional_skills'),
('Database Administration', 'professional_skills'),
('Salesmanship', 'professional_skills'),
('Photography', 'professional_skills'),
('Java Programming', 'professional_skills'),
('Python Programming', 'professional_skills'),
('Ruby Programming', 'professional_skills'),
('JavaScript Development', 'professional_skills'),
('PHP Programming', 'professional_skills'),
('iOS App Development', 'professional_skills'),
('Android App Development', 'professional_skills'),
('Web Development', 'professional_skills'),
('Data Science', 'professional_skills'),
('Machine Learning', 'professional_skills'),
('Market Research', 'professional_skills'),
('Financial Planning', 'professional_skills'),
('Business Development', 'professional_skills'),
('Strategic Planning', 'professional_skills'),
('Supply Chain Management', 'professional_skills'),
('E-commerce Management', 'professional_skills'),
('Entrepreneurship', 'professional_skills'),
('Risk Management', 'professional_skills'),
('International Business', 'professional_skills'),
('Welding', 'professional_skills'),
('Auto Mechanics', 'professional_skills'),
('Electrical Engineering', 'professional_skills'),
('Material Science', 'professional_skills'),
('Fluid Dynamics', 'professional_skills'),
('Lab Techniques', 'professional_skills'),
('Chemical Analysis', 'professional_skills'),
('Quality Control', 'professional_skills'),
('Robotics', 'professional_skills'),
('Thermodynamics', 'professional_skills'),
('Structural Engineering', 'professional_skills'),
('Astronomy', 'professional_skills'),
('Particle Physics', 'professional_skills'),
('Biochemistry', 'professional_skills'),
('Geological Surveying', 'professional_skills'),
('Environmental Science', 'professional_skills'),
('Nuclear Physics', 'professional_skills'),
('Renewable Energy', 'professional_skills'),
('Metallurgy', 'professional_skills'),
('Automotive Diagnostics', 'professional_skills'),
('Financial Modeling', 'professional_skills'),
('Risk Assessment', 'professional_skills'),
('Investment Analysis', 'professional_skills'),
('Tax Planning', 'professional_skills'),
('Portfolio Management', 'professional_skills'),
('UI/UX Design', 'professional_skills'),
('3D Modeling', 'professional_skills'),
('Typography Design', 'professional_skills'),
('Print Design', 'professional_skills'),
('Illustration', 'professional_skills'),
('Video Editing', 'professional_skills'),
('Motion Graphics', 'professional_skills'),
('Color Grading', 'professional_skills'),
('Scriptwriting', 'professional_skills'),
('Cinematography', 'professional_skills'),
('Supply Chain Optimization', 'professional_skills'),
('Inventory Management', 'professional_skills'),
('Freight and Transportation Management', 'professional_skills'),
('Warehouse Operations', 'professional_skills'),
('Demand Forecasting', 'professional_skills'),
('Curriculum Development', 'professional_skills'),
('Student Assessment', 'professional_skills'),
('Classroom Management', 'professional_skills'),
('Educational Technology', 'professional_skills'),
('Special Education', 'professional_skills'),
('Instructional Design', 'professional_skills'),
('Teacher Training', 'professional_skills'),
('E-Learning Development', 'professional_skills'),
('Adult Education', 'professional_skills'),
('Literacy Programs', 'professional_skills'),
('Music Composition', 'professional_skills'),
('Sound Engineering', 'professional_skills'),
('Music Production', 'professional_skills'),
('Music Theory', 'professional_skills'),
('Instrument Proficiency', 'professional_skills'),
('Piano Proficiency', 'professional_skills'),
('Guitar Playing', 'professional_skills'),
('Violin Performance', 'professional_skills'),
('Drumming Skills', 'professional_skills'),
('Flute Mastery', 'professional_skills'),
('Soccer Coaching', 'professional_skills'),
('Basketball Skills Training', 'professional_skills'),
('Tennis Instruction', 'professional_skills'),
('Swimming Coaching', 'professional_skills'),
('Golf Swing Analysis', 'professional_skills'),
('Yoga Instruction', 'professional_skills'),
('Personal Training', 'professional_skills'),
('Physical Therapy', 'professional_skills'),
('Nutrition Coaching', 'professional_skills'),
('Sports Psychology', 'professional_skills'),
('Hotel Management', 'professional_skills'),
('Culinary Arts', 'professional_skills'),
('Front Desk Operations', 'professional_skills'),
('Event Planning', 'professional_skills'),
('Customer Service in Hospitality', 'professional_skills'),
('Food and Beverage Management', 'professional_skills'),
('Bartending Skills', 'professional_skills'),
('Housekeeping and Cleaning', 'professional_skills'),
('Resort Operations', 'professional_skills'),
('Hospitality Marketing', 'professional_skills'),
('Medical Diagnostics', 'professional_skills'),
('Patient Care and Monitoring', 'professional_skills'),
('Surgical Techniques', 'professional_skills'),
('Pharmaceutical Knowledge', 'professional_skills'),
('Radiology and Imaging', 'professional_skills'),
('Emergency Medicine', 'professional_skills'),
('Physical Therapy', 'professional_skills'),
('Medical Research', 'professional_skills'),
('Nursing Specializations', 'professional_skills'),
('Epidemiology', 'professional_skills'),
('Experimental Design', 'professional_skills'),
('Data Analysis in R&D', 'professional_skills'),
('Innovation Management', 'professional_skills'),
('Research Project Planning', 'professional_skills'),
('Prototype Development', 'professional_skills');