/* Replace with your SQL commands */
create table if not exists person 
(
  id serial primary key,
  first_name varchar(255) not null,
  last_name varchar(255) not null,
  middle_name varchar(255) null,
  initials varchar(10) not null,
  email_prefix varchar(255) not null,
  gender varchar(10) not null,
  gender_shorten varchar(1) not null,
  title varchar(10) not null,
  entity_meta_table varchar(255) not null,
  constraint fk_entity_meta_table foreign key (entity_meta_table) references entity_meta(table_name) on delete cascade
);

insert into entity_meta (display_name, description, table_name, standalone, custom) values (
  'Person',
  '',
  'person',
  false,
  false
);

insert into column_meta (display_name, description, example, column_name, data_type, gen_opts_name, entity_meta_table) values (
  'Person First Name',
  '',
  'John, Mary',
  'first_name',
  'varchar(255)',
  'entityVarchar',
  'person'
),
(
  'Person Last Name',
  '',
  'Smith, Jones',
  'last_name',
  'varchar(255)',
  'entityVarchar',
  'person'
),
(
  'Person Middle Name',
  '',
  'Grace, William',
  'middle_name',
  'varchar(255)',
  'entityVarchar',
  'person'
),
(
  'Person Name Initials',
  'First letters of a person fullname, separated by a dot',
  'J.S, M.J.W',
  'initials',
  'varchar(10)',
  'entityVarchar',
  'person'
),
(
  'Email username',
  'Email username created from person fullname. Could be used as a prefix for email address',
  'johnsmith, maryjwatson',
  'email_prefix',
  'varchar(255)',
  'entityEmail',
  'person'
),
(
  'Gender',
  'Can be Male, Female or Non-Binary',
  'Male, Female, Non-Binary',
  'gender',
  'varchar(10)',
  'entityVarchar',
  'person'
),
(
  'Gender Shorten',
  'Can be M, F and N',
  'M, F, N',
  'gender_shorten',
  'varchar(1)',
  'entityVarchar',
  'person'
),
(
  'Person Formal Title',
  'Used to address individuals in various formal and informal contexts.',
  'Mr., Mrs., Ms., Dr., Prof.',
  'title',
  'varchar(10)',
  'entityVarchar',
  'person'
);

INSERT INTO person (first_name, last_name, middle_name, initials, email_prefix, gender, gender_shorten, title, entity_meta_table) VALUES 
  ('John', 'Doe', 'Michael', 'JMD', 'jmdoe', 'Male', 'M', 'Mr.', 'person'),
  ('Jane', 'Smith', 'Elizabeth', 'JSE', 'janesmith', 'Female', 'F', 'Mrs.', 'person'),
  ('Robert', 'Johnson', 'Lee', 'RJL', 'robertjohnson', 'Male', 'M', 'Mr.', 'person'),
  ('Emily', 'Brown', 'Grace', 'EBG', 'ebrown', 'Non-Binary', 'N', 'Ms.', 'person'),
  ('David', 'Wilson', 'James', 'DWJ', 'djwilson', 'Male', 'M', 'Dr.', 'person'),
  ('Sarah', 'Taylor', 'Daphne', 'ST', 'staylor123', 'Female', 'F', 'Ms.', 'person'),
  ('Michael', 'Anderson', 'Thomas', 'MAT', 'm.anderson', 'Male', 'M', 'Mr.', 'person'),
  ('Olivia', 'Martinez', 'Marie', 'OMM', 'oliviam', 'Female', 'F', 'Dr.', 'person'),
  ('William', 'White', 'Alexander', 'WWA', 'wwhite', 'Male', 'M', 'Mr.', 'person'),
  ('Sophia', 'Garcia', 'Isabella', 'SGI', 'sophiag123', 'Female', 'F', 'Mrs.', 'person'),
  ('Daniel', 'Miller', 'Joseph', 'DMJ', 'dm.joseph', 'Male', 'M', 'Mr.', 'person'),
  ('Ava', 'Wilson', 'Grace', 'AWG', 'ava_grace', 'Female', 'F', 'Ms.', 'person'),
  ('James', 'Anderson', 'Robert', 'JAR', 'jamesanderson123', 'Male', 'M', 'Mr.', 'person'),
  ('Sophie', 'Davis', 'Elizabeth', 'SDE', 'sophie.d', 'Female', 'F', 'Ms.', 'person'),
  ('Ethan', 'Clark', 'Michael', 'ECM', 'ethan.m.clark', 'Male', 'M', 'Mr.', 'person'),
  ('Oliver', 'Harris', 'William', 'OHW', 'oharris123', 'Male', 'M', 'Mr.', 'person'),
  ('Mia', 'Rodriguez', 'Isabella', 'MRI', 'mia_rodr', 'Non-Binary', 'N', 'Ms.', 'person'),
  ('Amelia', 'Lee', 'Emily', 'ALE', 'a.lee', 'Female', 'F', 'Ms.', 'person'),
  ('Benjamin', 'Garcia', 'Lucas', 'BGL', 'beng', 'Male', 'M', 'Mr.', 'person'),
  ('Emma', 'Martinez', 'Sophia', 'EMS', 'emma.m', 'Female', 'F', 'Ms.', 'person'),
  ('Liam', 'Brown', 'Alexander', 'LBA', 'liam_brown', 'Male', 'M', 'Mr.', 'person'),
  ('Charlotte', 'Smith', 'Grace', 'CSG', 'charlotte.grace', 'Female', 'F', 'Ms.', 'person'),
  ('Aiden', 'Johnson', 'Carter', 'AJC', 'aiden.c.j', 'Non-Binary', 'N', 'Mr.', 'person'),
  ('Ella', 'Williams', 'Madison', 'EWM', 'ellaw123', 'Female', 'F', 'Ms.', 'person'),
  ('Jackson', 'Taylor', 'Mason', 'JTM', 'jacksonm', 'Male', 'M', 'Mr.', 'person'),
  ('Harper', 'Jones', 'Ava', 'HJA', 'harper.j', 'Female', 'F', 'Ms.', 'person'),
  ('Sebastian', 'Moore', 'Henry', 'SMH', 'sebmoore', 'Non-Binary', 'N', 'Mr.', 'person'),
  ('Grace', 'Davis', 'Chloe', 'GDC', 'graced', 'Female', 'F', 'Ms.', 'person'),
  ('Noah', 'Walker', 'Ethan', 'NWE', 'noah.w', 'Male', 'M', 'Mr.', 'person'),
  ('Luna', 'Allen', 'Scarlett', 'LAS', 'luna.s', 'Non-Binary', 'N', 'Ms.', 'person'),
  ('Lucas', 'Young', 'Liam', 'LYL', 'l.young', 'Male', 'M', 'Mr.', 'person'),
  ('Evelyn', 'Rivera', 'Sofia', 'ERS', 'evelyn_rivera', 'Female', 'F', 'Prof.', 'person'),
  ('Logan', 'Cruz', 'Aiden', 'LCA', 'logan.a.cruz', 'Male', 'M', 'Mr.', 'person'),
  ('Aria', 'Flores', 'Mia', 'AFM', 'aria_mia', 'Female', 'F', 'Prof.', 'person'),
  ('Carter', 'Perez', 'Elijah', 'CPE', 'carter.p', 'Male', 'M', 'Mr.', 'person'),
  ('Avery', 'Lopez', 'Ella', 'ALE', 'a.lopez', 'Female', 'F', 'Prof.', 'person'),
  ('Jayden', 'Gonzalez', 'James', 'JGJ', 'jaydenj', 'Male', 'M', 'Mr.', 'person'),
  ('Layla', 'Sanchez', 'Liam', 'LSSL', 'layla.s', 'Female', 'F', 'Dr.', 'person'),
  ('Mateo', 'Rivera', 'Elena', 'MRE', 'mateorivera', 'Male', 'M', 'Mr.', 'person'),
  ('Nora', 'Perez', 'Oliver', 'NPO', 'nora.perez', 'Female', 'F', 'Dr.', 'person'),
  ('Gabriel', 'Ramirez', 'Alexander', 'GRA', 'gabrielr123', 'Male', 'M', 'Mr.', 'person'),
  ('Addison', 'Gomez', 'Lucas', 'AGL', 'addison.l', 'Female', 'F', 'Dr.', 'person'),
  ('Leo', 'Ortiz', 'Ava', 'LOA', 'leo.ortiz', 'Male', 'M', 'Mr.', 'person'),
  ('Elizabeth', 'Torres', 'Grace', 'ETG', 'eliz_torres', 'Female', 'F', 'Dr.', 'person'),
  ('Jack', 'Hernandez', 'Liam', 'JHL', 'jack_l.h', 'Male', 'M', 'Mr.', 'person'),
  ('Mila', 'Gutierrez', 'Emma', 'MGE', 'mila_e', 'Female', 'F', 'Mrs.', 'person'),
  ('Wyatt', 'Vargas', 'Ethan', 'WVE', 'wyatt.v', 'Male', 'M', 'Dr.', 'person'),
  ('Chloe', 'Santiago', 'Isabella', 'CSI', 'chloe_s', 'Female', 'F', 'Mrs.', 'person'),
  ('Owen', 'Castillo', 'Benjamin', 'OCB', 'owenc', 'Male', 'M', 'Mr.', 'person'),
  ('Lily', 'Gomez', 'Olivia', 'LGO', 'lilyg123', 'Female', 'F', 'Mrs.', 'person'),
  ('Samuel', 'Diaz', 'Ava', 'SDA', 'sam.diaz', 'Male', 'M', 'Mr.', 'person'),
  ('Aurora', 'Reyes', 'Sophia', 'ARS', 'aurora.reyes', 'Female', 'F', 'Ms.', 'person'),
  ('Haruki', 'Tanaka', 'Akira', 'HTA', 'harukitan', 'Male', 'M', 'Mr.', 'person'),
  ('Mei', 'Chen', 'Ling', 'MCL', 'meichen', 'Female', 'F', 'Mrs.', 'person'),
  ('Rajesh', 'Patel', 'Amit', 'RPA', 'raj_pat', 'Male', 'M', 'Mr.', 'person'),
  ('Sakura', 'Yamamoto', 'Hiroshi', 'SYH', 'sakura.h', 'Female', 'F', 'Ms.', 'person'),
  ('Ji-hoon', 'Kim', 'Min-jun', 'JHK', 'j.hoon', 'Male', 'M', 'Mr.', 'person'),
  ('Hyun-ju', 'Lee', 'Min-ji', 'HJLM', 'hyun_lee', 'Female', 'F', 'Mrs.', 'person'),
  ('Rajiv', 'Gupta', 'Vikram', 'RGV', 'rajiv.g', 'Male', 'M', 'Mr.', 'person'),
  ('Aaradhya', 'Rao', 'Amita', 'ARR', 'aaradhya', 'Female', 'F', 'Ms.', 'person'),
  ('Wei', 'Li', 'Chen', 'WLC', 'wei_li', 'Male', 'M', 'Mr.', 'person'),
  ('Yuki', 'Nakamura', 'Hana', 'YNH', 'yuki_h', 'Female', 'F', 'Mrs.', 'person');